#!/usr/bin/env python3
"""
STEP-BY-STEP GUIDE: Adding Expert Targeting Interests
For ai-filo-agent Campaign - Detailed Targeting Section
"""

def print_targeting_setup_guide():
    print("🎯 DETAILED TARGETING SETUP - STEP BY STEP")
    print("="*60)
    print()
    print("📍 CURRENT STATUS: Detailed targeting is empty")
    print("🎯 GOAL: Add expert-selected high-converting interests")
    print()
    
    print("📱 STEP-BY-STEP INSTRUCTIONS:")
    print("="*40)
    print()
    
    print("1️⃣ CLICK ON 'DETAILED TARGETING' SECTION")
    print("   • In your current screen, click where it says:")
    print("   • 'All demographics, interests and behaviours'")
    print()
    
    print("2️⃣ ADD TIER 1 INTERESTS (HIGHEST CONVERTING)")
    print("   • Click 'Browse' or the search box")
    print("   • Type and add these ONE BY ONE:")
    print("   ✅ Sunglasses")
    print("   ✅ Ray-Ban")
    print("   ✅ Oakley") 
    print("   ✅ Eyewear")
    print("   • Make sure each one shows up as a blue tag")
    print()
    
    print("3️⃣ ADD TIER 2 INTERESTS (HIGH CONVERTING)")
    print("   • Continue adding these:")
    print("   ✅ Fashion")
    print("   ✅ Luxury goods")
    print("   ✅ Designer clothing")
    print("   ✅ Fashion accessory")
    print()
    
    print("4️⃣ ADD TIER 3 INTERESTS (SUPPORTING)")
    print("   • Add these for broader reach:")
    print("   ✅ Online shopping")
    print("   ✅ Shopping")
    print("   ✅ Photography")
    print("   ✅ Travel")
    print()
    
    print("5️⃣ VERIFY AUDIENCE SIZE")
    print("   • Check the audience size indicator")
    print("   • Should show: 2-8 million people in India")
    print("   • If too small (under 1M): Remove some interests")
    print("   • If too large (over 10M): Add more specific interests")
    print()
    
    print("6️⃣ ADD EXCLUSIONS (CRITICAL)")
    print("   • Scroll down to find 'Exclude People' section")
    print("   • Click 'Exclude' → 'Interests'")
    print("   • Add these exclusions:")
    print("   ❌ Discount shopping")
    print("   ❌ Cheap products") 
    print("   ❌ Bargain hunters")
    print("   ❌ Coupons")
    print()
    
    print("7️⃣ SAVE CHANGES")
    print("   • Click 'Publish' or 'Save' button")
    print("   • Wait for confirmation message")
    print()
    
    print("🔍 WHAT YOU SHOULD SEE AFTER SETUP:")
    print("="*40)
    print("• Detailed targeting: 12+ interests listed")
    print("• Audience size: 2-8 million in India")
    print("• Age: 25-45 ✅")
    print("• Gender: All genders ✅")
    print("• Location: India ✅")
    print()
    
    print("⚠️ TROUBLESHOOTING:")
    print("="*20)
    print("❓ Can't find an interest?")
    print("   → Try variations: 'Sunglass' vs 'Sunglasses'")
    print("   → Use 'Browse' → 'Interests' → Search")
    print()
    print("❓ Audience too small?")
    print("   → Remove some specific brand interests")
    print("   → Keep broader terms like 'Fashion', 'Shopping'")
    print()
    print("❓ Audience too large?")
    print("   → Add more specific interests")
    print("   → Use 'AND' connection instead of 'OR'")
    print()
    
    print("🎯 EXPECTED RESULTS AFTER SETUP:")
    print("="*35)
    print("• CTR: 2.5-4.5% (vs current 1-2%)")
    print("• CPC: ₹8-15 (vs current ₹20+)")
    print("• ROAS: 7-12 (vs current 5.29)")
    print("• Better quality traffic")
    print("• Higher conversion rates")
    print()
    
    print("⏰ TIMELINE:")
    print("• Setup time: 5-10 minutes")
    print("• First results: 2-4 hours")
    print("• Full optimization: 24-48 hours")
    print()
    
    print("🚀 PRIORITY ORDER:")
    print("1. Add Tier 1 interests FIRST (most important)")
    print("2. Add exclusions (saves budget)")
    print("3. Add Tier 2 & 3 interests")
    print("4. Verify audience size is 2-8M")
    print("5. Publish changes")

def print_visual_guide():
    print("\n" + "="*60)
    print("📱 VISUAL GUIDE - WHAT TO CLICK")
    print("="*60)
    print()
    print("CURRENT SCREEN → NEXT ACTION:")
    print()
    print("┌─────────────────────────────────────┐")
    print("│ Detailed targeting                  │")
    print("│ All demographics, interests and     │ ← CLICK HERE")
    print("│ behaviours                          │")
    print("└─────────────────────────────────────┘")
    print()
    print("AFTER CLICKING, YOU'LL SEE:")
    print()
    print("┌─────────────────────────────────────┐")
    print("│ Include people who match            │")
    print("│ ┌─────────────────────────────────┐ │")
    print("│ │ Browse or type to add interests │ │ ← TYPE HERE")
    print("│ └─────────────────────────────────┘ │")
    print("└─────────────────────────────────────┘")
    print()
    print("TYPE IN THIS ORDER:")
    print("1. 'Sunglasses' → Enter")
    print("2. 'Ray-Ban' → Enter") 
    print("3. 'Oakley' → Enter")
    print("4. 'Eyewear' → Enter")
    print("5. Continue with other interests...")

if __name__ == "__main__":
    print_targeting_setup_guide()
    print_visual_guide()
    
    print("\n🎯 QUICK CHECKLIST:")
    print("□ Click 'Detailed targeting' section")
    print("□ Add Sunglasses, Ray-Ban, Oakley, Eyewear")
    print("□ Add Fashion, Luxury goods, Designer clothing")
    print("□ Add Online shopping, Shopping, Photography")
    print("□ Add exclusions: Discount shopping, Cheap products")
    print("□ Verify audience size: 2-8 million")
    print("□ Click Publish/Save")
    print()
    print("🚀 YOU'RE 5 MINUTES AWAY FROM 2X BETTER PERFORMANCE!")
